### ISSUE TITLE
Current trunk of xia2 borken when processing I23 data

### ISSUE THREAD

**Issue by graeme-winter** [xia2/xia2#124] opened 2017-05-19 08:36 UTC
```
[gw56@ws133 12.5]$ !xia
xia2.small_molecule $OLDPWD
Environment configuration...
Python => /dls/science/users/gw56/svn/cctbx/build/../base/bin/python2.7
CCTBX => /dls/science/users/gw56/svn/cctbx/modules
CCP4 => /dls_sw/apps/ccp4/64/7.0/update35/ccp4-7.0
CLIBD => /dls_sw/apps/ccp4/64/7.0/update35/ccp4-7.0/lib/data
CCP4_SCR => /tmp/tmpTkW9Pv
Starting directory: /dls/tmp/gw56/ge_i23/12.5
Working directory: /dls/tmp/gw56/ge_i23/12.5
Free space:        2601.75 GB
Host: ws133
Contact: xia2.support@gmail.com
XIA2 0.5.303-g1bf31e7
DIALS 1.dev.1373-g5dcb066
CCP4 7.0.035
Command line: xia2 small_molecule=true /dls/i23/data/2017/nr16818-43/20170518/germanate_12p5keV
Status: error "can't convert negative value to unsigned"
Please send the contents of xia2.txt, xia2.error and xia2-debug.txt to:
xia2.support@gmail.com
[gw56@ws133 12.5]$ cat xia2.error 
Traceback (most recent call last):
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/command_line/xia2_main.py", line 298, in run
    xinfo = xia2_main()
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/command_line/xia2_main.py", line 47, in xia2_main
    CommandLine = get_command_line()
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/Applications/xia2_main.py", line 114, in get_command_line
    write_xinfo(xinfo, directories)
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/Applications/xia2setup.py", line 535, in write_xinfo
    print_sweeps(fout)
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/Applications/xia2setup.py", line 418, in print_sweeps
    beam_centre = compute_beam_centre(s)
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/Modules/LabelitBeamCentre.py", line 33, in compute_beam_centre
    beam_centre = sweep.get_beam_centre()
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/Schema/Sweep.py", line 123, in get_beam_centre
    return get_beam_centre(detector, beam)
  File "/dls/science/users/gw56/svn/cctbx/modules/xia2/Schema/Interfaces/FrameProcessor.py", line 349, in get_beam_centre
    panel = detector[panel_id]
OverflowError: can't convert negative value to unsigned

```

#1 need test case for this beamline in regression

**Comment by graeme-winter** [comment] 2017-05-19 08:43
Interesting - also issue with current release

Worked the other day on a different set, possibly is problem with these images...

**Comment by rjgildea** [comment] 2017-05-19 08:48
The problem is in get_beam_centre() function:
https://github.com/xia2/xia2/blob/master/Schema/Interfaces/FrameProcessor.py#L341

dials.show seems to calculate the beam_centre without problem:
```
$ dials.show /dls/i23/data/2017/nr16818-43/20170518/germanate_12p5keV/data_1_0001.cbf | grep "Beam centre"
Beam centre (mm): panel 23, (191.90,-600.93)
Beam centre (px): panel 23, (1115.70,-3495.19)
```

**Comment by rjgildea** [comment] 2017-05-19 08:50
dials.show uses a different function get the beam centre:
https://github.com/dials/dials/blob/master/command_line/show.py#L43
I'm not sure whether that gives the correct answer either in this case...

**Comment by graeme-winter** [comment] 2017-05-19 11:25
```
# Detector_Voffset 0.00000 m
# Beam_xy (1067.00, 2590.00) pixels
# Flux 805079809.499957
# Filter_transmission 0.0000
# Start_angle -210.0000 deg.

```

from hdr

**Comment by graeme-winter** [comment] 2017-05-19 11:28
Yesterday's data

```
# Detector_distance -0.00000 m
# Detector_Voffset 0.00000 m
# Beam_xy (1067.00, 2590.00) pixels
# Flux 626771494.787359
# Filter_transmission 0.0000
# Start_angle -210.0000 deg.

```

pretty similar...

**Comment by rjgildea** [comment] 2017-05-19 11:29
Did yesterday's data work?

**Comment by rjgildea** [comment] 2017-05-19 11:32
Sensible beam centre:
```
$ dials.show /dls/i23/data/2017/nr16818-43/20170517/germanate_kappa_0_phi_0_9keV/data_2_0001.cbf | grep "Beam centre"
Beam centre (mm): panel 12, (184.90,8.60)
Beam centre (px): panel 12, (1075.00,49.96)
```
Not sensible beam centre:
```
$ dials.show /dls/i23/data/2017/nr16818-43/20170518/germanate_12p5keV/data_1_0001.cbf | grep "Beam centre"
Beam centre (mm): panel 23, (191.90,-600.93)
Beam centre (px): panel 23, (1115.70,-3495.19)
```

**Comment by graeme-winter** [comment] 2017-05-19 11:33
yesterday still works fine hmmm

**Comment by rjgildea** [comment] 2017-05-19 11:35
Wavelength and detector distance main differences in experimental geometry:
```
$ diff <(strings /dls/i23/data/2017/nr16818-43/20170517/germanate_kappa_0_phi_0_9keV/data_2_0001.cbf) <(strings /dls/i23/data/2017/nr16818-43/20170518/germanate_12p5keV/data_1_0001.cbf)
22c22
< # Wavelength 1.37760 A
---
> # Wavelength 0.99187 A
24c24
< # Detector_distance -0.00000 m
---
> # Detector_distance 0.24000 m
```

**Comment by graeme-winter** [comment] 2017-05-19 11:52
oh if detector distance is != 0 could get some interesting results

will look closer... good spot

**Comment by graeme-winter** [comment] 2017-05-25 06:03
Suspect @rjgildea fixed this yesterday in https://github.com/cctbx/cctbx_project/commit/d7ae073e77e4771069168b20d7237bfbb0467c38

**Comment by graeme-winter** [comment] 2017-05-25 06:15
OK, while it may not be broken _per se_ there is still something not right - suspect misindexing or something similar, incorrect derived beam centre at not-close distance?

``
For AUTOMATIC/DEFAULT/NATIVE                Suggested   Low    High  Overall
High resolution limit                           1.83    4.95    1.83    1.00
Low resolution limit                           20.92   20.92    1.86   20.92
Completeness                                  100.0   100.0   100.0    86.0
Multiplicity                                    7.8     7.0     6.6     5.6
I/sigma                                         1.6     0.6     1.2     0.9
Rmerge(I)                                     0.880   0.842   0.898   0.933
Rmeas(I)                                      0.943   0.934   0.970   1.021
Rpim(I)                                       0.333   0.387   0.362   0.404
CC half                                       0.397   0.845   0.328   0.036
Total observations                            16259     833     691   59929
Total unique                                   2078     119     104   10704
Assuming spacegroup: I m -3
Unit cell (with estimated std devs):
51.2421(2) 51.2421(2) 51.2421(2)
```

should be ++ better than this

**Comment by rjgildea** [comment] 2017-05-25 08:50
This was broken because of "historical reasons". Should now be fixed by https://github.com/cctbx/cctbx_project/commit/13813019c290e9073983709db45554427156d08e
```
For AUTOMATIC/DEFAULT/NATIVE                Suggested   Low    High  Overall
High resolution limit                           0.98    2.66    0.98    0.98
Low resolution limit                           18.15   18.15    1.00   18.15
Completeness                                   96.8   100.0    16.3    95.2
Multiplicity                                   10.0    14.7     1.1    10.0
I/sigma                                        25.2    55.7     4.4    25.2
Rmerge(I)                                     0.046   0.028   0.133   0.046
Rmeas(I)                                      0.048   0.029   0.178   0.048
Rpim(I)                                       0.014   0.008   0.118   0.014
CC half                                       1.000   1.000   0.955   1.000
Total observations                            60592    5957      57   60597
Total unique                                   6068     405      52    6073
Assuming spacegroup: I a -3 d
Unit cell (with estimated std devs):
51.33025(4) 51.33025(4) 51.33025(4)
90.0        90.0        90.0    
```

**Closed by rjgildea** 2017-05-25 08:50 UTC
